<?xml  version='1.0' encoding='utf-8' ?>
<xs:schema targetNamespace="http://www.fixm.aero/ext/nas/4.4" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:nas="http://www.fixm.aero/ext/nas/4.4" xmlns:fb="http://www.fixm.aero/base/4.3" elementFormDefault="qualified" version="4.4.0">
	<xs:annotation>
		<xs:documentation>The NasAirspace package contains NAS specific extensions to FIXM Core airspace fields.

=========================================== 
Copyright (c) 2025 US Federal Aviation Administration (FAA)
=========================================== 
All rights reserved. 
          
Redistribution and use in source and binary forms, with or without modification, are permitted provided that the following conditions are met: 
	- Redistributions of source code must retain the above copyright notice, this list of conditions and the disclaimer.
	- Redistributions in binary form must reproduce the above copyright notice, this list of conditions and the disclaimer in the documentation and/or other materials provided with the distribution.
	- The name of US FAA or the names of its contributors may not be used to endorse or promote products derived from this specification without specific prior written permission.
          
DISCLAIMER 
          
THIS SPECIFICATION IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE. 
          
========================================== 
Editorial note: this license is an instance of the BSD license template as provided by the Open Source Initiative: 
http://www.opensource.org/licenses/bsd-license.php 
          
The authoritative reference for FIXM is www.FIXM.aero. 
          
Details on the US FAA: http://www.faa.gov/</xs:documentation>
	</xs:annotation>
	<xs:import namespace="http://www.fixm.aero/base/4.3" schemaLocation="../../core/base/Base.xsd"/>
	<xs:simpleType name="TfmsRouteTypeType">
		<xs:annotation>
			<xs:documentation>Provides the route type for a Departure Procedure or a Standard Instrument Arrival.</xs:documentation>
		</xs:annotation>
		<xs:restriction base="xs:string">
			<xs:enumeration value="AIRWAY">
				<xs:annotation>
					<xs:documentation>Airway Route</xs:documentation>
				</xs:annotation>
			</xs:enumeration>
			<xs:enumeration value="CODED_ROUTE">
				<xs:annotation>
					<xs:documentation>Coded Departure Route</xs:documentation>
				</xs:annotation>
			</xs:enumeration>
			<xs:enumeration value="DIRECT">
				<xs:annotation>
					<xs:documentation>Direct Route</xs:documentation>
				</xs:annotation>
			</xs:enumeration>
			<xs:enumeration value="SID">
				<xs:annotation>
					<xs:documentation>RNAV Standard Instrument Departure</xs:documentation>
				</xs:annotation>
			</xs:enumeration>
			<xs:enumeration value="STAR">
				<xs:annotation>
					<xs:documentation>Standard Terminal Arrival</xs:documentation>
				</xs:annotation>
			</xs:enumeration>
			<xs:enumeration value="AAR">
				<xs:annotation>
					<xs:documentation>Adapted Arrival Route</xs:documentation>
				</xs:annotation>
			</xs:enumeration>
			<xs:enumeration value="ADR">
				<xs:annotation>
					<xs:documentation>Adapted Departure Route</xs:documentation>
				</xs:annotation>
			</xs:enumeration>
			<xs:enumeration value="ADAR">
				<xs:annotation>
					<xs:documentation>Adapted Departure and Arrival Route</xs:documentation>
				</xs:annotation>
			</xs:enumeration>
			<xs:enumeration value="UNKNOWN">
				<xs:annotation>
					<xs:documentation>Unknown Route Type</xs:documentation>
				</xs:annotation>
			</xs:enumeration>
			<xs:enumeration value="OTHER">
				<xs:annotation>
					<xs:documentation>Other Route Type</xs:documentation>
				</xs:annotation>
			</xs:enumeration>
		</xs:restriction>
	</xs:simpleType>
	<xs:complexType name="InstrumentRouteDesignatorType">
		<xs:annotation>
			<xs:documentation>This is a route designator from the flight plan route of flight.  It can be defined as one of several specific TFMS route types.</xs:documentation>
		</xs:annotation>
		<xs:sequence>
			<xs:element name="designator" type="fb:SidStarDesignatorType" minOccurs="0" maxOccurs="1" nillable="true">
				<xs:annotation>
					<xs:documentation>The name of the instrument route.</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="routeType" type="nas:TfmsRouteTypeType" minOccurs="0" maxOccurs="1" nillable="true">
				<xs:annotation>
					<xs:documentation>Provides the route type for a Departure Procedure or a Standard Instrument Arrival.</xs:documentation>
				</xs:annotation>
			</xs:element>
		</xs:sequence>
	</xs:complexType>
</xs:schema>