<?xml  version='1.0' encoding='utf-8' ?>
<xs:schema targetNamespace="http://www.fixm.aero/ext/nas/4.4" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:nas="http://www.fixm.aero/ext/nas/4.4" xmlns:fb="http://www.fixm.aero/base/4.3" elementFormDefault="qualified" version="4.4.0">
	<xs:annotation>
		<xs:documentation>The NasFlightData package contains NAS specific extensions to the FIXM Core FlightData package.

=========================================== 
Copyright (c) 2025 US Federal Aviation Administration (FAA)
=========================================== 
All rights reserved. 
          
Redistribution and use in source and binary forms, with or without modification, are permitted provided that the following conditions are met: 
	- Redistributions of source code must retain the above copyright notice, this list of conditions and the disclaimer.
	- Redistributions in binary form must reproduce the above copyright notice, this list of conditions and the disclaimer in the documentation and/or other materials provided with the distribution.
	- The name of US FAA or the names of its contributors may not be used to endorse or promote products derived from this specification without specific prior written permission.
          
DISCLAIMER 
          
THIS SPECIFICATION IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE. 
          
========================================== 
Editorial note: this license is an instance of the BSD license template as provided by the Open Source Initiative: 
http://www.opensource.org/licenses/bsd-license.php 
          
The authoritative reference for FIXM is www.FIXM.aero. 
          
Details on the US FAA: http://www.faa.gov/</xs:documentation>
	</xs:annotation>
	<xs:import namespace="http://www.fixm.aero/base/4.3" schemaLocation="../../core/base/Base.xsd"/>
	<xs:include schemaLocation="NasCommon.xsd"/>
	<xs:include schemaLocation="NasTmiData.xsd"/>
	<xs:include schemaLocation="NasStatus.xsd"/>
	<xs:simpleType name="AdaptedIndicatorTypeType">
		<xs:annotation>
			<xs:documentation>Specifies which ERAM adapted field (A-Y) the indicator comes from.</xs:documentation>
		</xs:annotation>
		<xs:restriction base="fb:CharacterStringType">
			<xs:pattern value="[A-Y]"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="AdsbTargetIdentifierType">
		<xs:annotation>
			<xs:documentation>ADS-B Flight ID is the Target Identification reported by the aircraft in FRN 12 of an ADS-B broadcast. This is generally the aircraft callsign.
A percent symbol '%' indicates the character was reported by the aircraft as unavailable.
A question mark '?' indicates the character was encoded using a value defined as illegal by the SBS ICD.
A single uppercase letter 'M' signifies the ADS-B Flight ID was not provided.
The valid characters for the Flight ID are alphanumerics, space, '%' and '?'.</xs:documentation>
		</xs:annotation>
		<xs:restriction base="fb:CharacterStringType">
			<xs:pattern value="[A-Z0-9 %?]{1,8}"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="ComputerIdentificationType">
		<xs:annotation>
			<xs:documentation>A unique identifier assigned by a particular system within a particular facility.  Typically ERAM within an ARTCC.</xs:documentation>
		</xs:annotation>
		<xs:restriction base="fb:CharacterStringType">
			<xs:pattern value="[A-Z0-9]{3}"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="ComputerIdSystemType">
		<xs:annotation>
			<xs:documentation>The system that assigned the computer identifier.</xs:documentation>
		</xs:annotation>
		<xs:restriction base="xs:string">
			<xs:enumeration value="TFMS">
				<xs:annotation>
					<xs:documentation>Traffic Flow Management System</xs:documentation>
				</xs:annotation>
			</xs:enumeration>
			<xs:enumeration value="HCS">
				<xs:annotation>
					<xs:documentation>Host Computer System</xs:documentation>
				</xs:annotation>
			</xs:enumeration>
			<xs:enumeration value="CTAS">
				<xs:annotation>
					<xs:documentation>Center TRACON Automation System</xs:documentation>
				</xs:annotation>
			</xs:enumeration>
			<xs:enumeration value="TBFM">
				<xs:annotation>
					<xs:documentation>Time Based Flow Management </xs:documentation>
				</xs:annotation>
			</xs:enumeration>
			<xs:enumeration value="ETMS">
				<xs:annotation>
					<xs:documentation>Enhanced Traffic Management System</xs:documentation>
				</xs:annotation>
			</xs:enumeration>
			<xs:enumeration value="ERAM">
				<xs:annotation>
					<xs:documentation>En Route Automation Modernization</xs:documentation>
				</xs:annotation>
			</xs:enumeration>
			<xs:enumeration value="STDDS">
				<xs:annotation>
					<xs:documentation>SWIM Terminal Data Distribution System</xs:documentation>
				</xs:annotation>
			</xs:enumeration>
			<xs:enumeration value="ODAPS">
				<xs:annotation>
					<xs:documentation>Oceanic Display and Planning System</xs:documentation>
				</xs:annotation>
			</xs:enumeration>
			<xs:enumeration value="OTHER">
				<xs:annotation>
					<xs:documentation>Other System</xs:documentation>
				</xs:annotation>
			</xs:enumeration>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="CoordinationTimeTypeType">
		<xs:annotation>
			<xs:documentation>The indicator for the type of Coordination Time.</xs:documentation>
		</xs:annotation>
		<xs:restriction base="xs:string">
			<xs:enumeration value="P">
				<xs:annotation>
					<xs:documentation>Proposed flight plan preparing for departure</xs:documentation>
				</xs:annotation>
			</xs:enumeration>
			<xs:enumeration value="D">
				<xs:annotation>
					<xs:documentation>Flight plan has departed from the departure airport</xs:documentation>
				</xs:annotation>
			</xs:enumeration>
			<xs:enumeration value="E">
				<xs:annotation>
					<xs:documentation>Active flight plan, aircraft is flying.              </xs:documentation>
				</xs:annotation>
			</xs:enumeration>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="DataBlockIndicatorType">
		<xs:annotation>
			<xs:documentation>A list of possible indicators in the track's data block.</xs:documentation>
		</xs:annotation>
		<xs:restriction base="xs:string">
			<xs:enumeration value="AMB">
				<xs:annotation>
					<xs:documentation>Ambiguity, a disparity of more than 2 miles exists between the position declared for a target by STARS and another facility's computer declared position during inter-facility handoff.</xs:documentation>
				</xs:annotation>
			</xs:enumeration>
			<xs:enumeration value="AUTO_HANDOFF_DISABLE">
				<xs:annotation>
					<xs:documentation>The "Auto Handoff" feature in STARS, which automatically initiates a handoff to the next sector, has been disabled and the controller must manually initiate a handoff.</xs:documentation>
				</xs:annotation>
			</xs:enumeration>
			<xs:enumeration value="CX">
				<xs:annotation>
					<xs:documentation>Handoff Canceled, appears when a handoff has been canceled by the receiving facility, requiring the transferring controller to initiate a manual handoff.</xs:documentation>
				</xs:annotation>
			</xs:enumeration>
			<xs:enumeration value="DM">
				<xs:annotation>
					<xs:documentation>Departure Message, usually this is displayed if there was previously a DM on an aircraft, followed by a "Hold Message".  Controller is required to manually enter a departure message into STARS system.</xs:documentation>
				</xs:annotation>
			</xs:enumeration>
			<xs:enumeration value="FP">
				<xs:annotation>
					<xs:documentation>Flight Plan Transfer Failed, appears in a handoff between two terminal facilities rather than between a terminal facility and an en route facility.  It means the flight plan transfer has failed necessitating a manual handoff.</xs:documentation>
				</xs:annotation>
			</xs:enumeration>
			<xs:enumeration value="IF">
				<xs:annotation>
					<xs:documentation>Interfacility Fail, appears when an automated handoff cannot be completed by STARS and the controller must make a manual handoff.</xs:documentation>
				</xs:annotation>
			</xs:enumeration>
			<xs:enumeration value="NAT">
				<xs:annotation>
					<xs:documentation>Not Automated Radar Tracking System (ARTS) Tracked, the STARS system cannot track a particular target for some reason Note: The STDDS TAIS will not publish this field when the received AIG200 message indicates an interface version of 0.</xs:documentation>
				</xs:annotation>
			</xs:enumeration>
			<xs:enumeration value="OLD">
				<xs:annotation>
					<xs:documentation>Flight Plan Data Old, appears in an ARTCC to TRACON handoff.  The data in the flight plan is old or perhaps it exceeds the time limits in the system so uncertainty exists. The STARS system is receiving some data from En Route Automation Modernization (ERAM) but no track updates, so it is unsure of the position of the aircraft, probably because the aircraft is outside of the range of the terminal radar.</xs:documentation>
				</xs:annotation>
			</xs:enumeration>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="DataBlockIndicatorListType">
		<xs:annotation>
			<xs:documentation>Helper simpleType that allows representation of data block indicators as a list.</xs:documentation>
		</xs:annotation>
		<xs:list itemType="nas:DataBlockIndicatorType"/>
	</xs:simpleType>
	<xs:simpleType name="DiversionRecoveryIndicatorType">
		<xs:annotation>
			<xs:documentation>Indicates whether a flight is in diversion recovery.</xs:documentation>
		</xs:annotation>
		<xs:restriction base="xs:string">
			<xs:enumeration value="DIVERSION_RECOVERY">
				<xs:annotation>
					<xs:documentation>The flight is in diversion recovery.</xs:documentation>
				</xs:annotation>
			</xs:enumeration>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="DiversionStateType">
		<xs:annotation>
			<xs:documentation>Indicator used to define the diversion state of a flight.</xs:documentation>
		</xs:annotation>
		<xs:restriction base="xs:string">
			<xs:enumeration value="AIRBORN_NOCTL">
				<xs:annotation>
					<xs:documentation>Airborne - Not Controlled</xs:documentation>
				</xs:annotation>
			</xs:enumeration>
			<xs:enumeration value="AIRBORN_CTL">
				<xs:annotation>
					<xs:documentation>Airborne - Controlled</xs:documentation>
				</xs:annotation>
			</xs:enumeration>
			<xs:enumeration value="GROUND_NOCTL">
				<xs:annotation>
					<xs:documentation>Ground - Not Controlled</xs:documentation>
				</xs:annotation>
			</xs:enumeration>
			<xs:enumeration value="GROUND_CTL">
				<xs:annotation>
					<xs:documentation>Ground - Controlled</xs:documentation>
				</xs:annotation>
			</xs:enumeration>
			<xs:enumeration value="NO_DIVERSION">
				<xs:annotation>
					<xs:documentation>No Diversion</xs:documentation>
				</xs:annotation>
			</xs:enumeration>
			<xs:enumeration value="DIVERSION_CANCELLED">
				<xs:annotation>
					<xs:documentation>Diversion Canceled</xs:documentation>
				</xs:annotation>
			</xs:enumeration>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="FlightDelayReasonType">
		<xs:annotation>
			<xs:documentation>For a delayed flight, it provides the reason for the delay.</xs:documentation>
		</xs:annotation>
		<xs:restriction base="xs:string">
			<xs:enumeration value="ALD">
				<xs:annotation>
					<xs:documentation>Indicates that the CDM Participant has at some point sent in a departure time estimate (via an FC or FM) for a flight that was later than the estimate previously in the database.</xs:documentation>
				</xs:annotation>
			</xs:enumeration>
			<xs:enumeration value="GDP">
				<xs:annotation>
					<xs:documentation>Indicates that the flight has at some point been controlled by a GDP-Initial or GDP-Revision.</xs:documentation>
				</xs:annotation>
			</xs:enumeration>
			<xs:enumeration value="AFP">
				<xs:annotation>
					<xs:documentation>Indicates that the flight has at some point been controlled by an AFP-Initial or AFP-Revision.</xs:documentation>
				</xs:annotation>
			</xs:enumeration>
			<xs:enumeration value="CTOP">
				<xs:annotation>
					<xs:documentation>Indicates that the flight has at some point been controlled by a CTOP-Initial or CTOP-Revision.</xs:documentation>
				</xs:annotation>
			</xs:enumeration>
			<xs:enumeration value="DAS">
				<xs:annotation>
					<xs:documentation>Indicates that a DAS delay has been applied to this flight.</xs:documentation>
				</xs:annotation>
			</xs:enumeration>
			<xs:enumeration value="GSD">
				<xs:annotation>
					<xs:documentation>Indicates the flight has at some point been part of a GDP-Ground Stop program.</xs:documentation>
				</xs:annotation>
			</xs:enumeration>
			<xs:enumeration value="TOD">
				<xs:annotation>
					<xs:documentation>Indicates that TFMS-Core is delaying this flight due to the fact that it has not departed as projected. The TOD status precedes a time out cancel (TO). A time out delay occurs when a flight has a flight plan message, its departure time is in the past, and it has not been activated yet. In this case, TFMS-Core moves the flight back in time in 5-minute increments until canceled by time out logic (see TO field). If TFMS-Core receives a new message for this flight moving its departure time into the future, the TOD flag is cleared indicating that the flight is no longer in time out delay. Time out delay logic is applied only to the same flight as time out cancel logic (see TO field).</xs:documentation>
				</xs:annotation>
			</xs:enumeration>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="FlightDelayReasonListType">
		<xs:annotation>
			<xs:documentation>Helper simpleType to allow for enumerated lists in FIXM.</xs:documentation>
		</xs:annotation>
		<xs:list itemType="nas:FlightDelayReasonType"/>
	</xs:simpleType>
	<xs:simpleType name="FlightDelayStatusType">
		<xs:annotation>
			<xs:documentation>Provides the delay status for a flight.</xs:documentation>
		</xs:annotation>
		<xs:restriction base="xs:string">
			<xs:enumeration value="DELAYED">
				<xs:annotation>
					<xs:documentation>The flight is delayed.</xs:documentation>
				</xs:annotation>
			</xs:enumeration>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="FlightPlanRevisionNumberType">
		<xs:annotation>
			<xs:documentation>Represents the current revision number of the flight plan.</xs:documentation>
		</xs:annotation>
		<xs:restriction base="fb:CountType">
			<xs:maxInclusive value="99"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="LeaderLineDirectionType">
		<xs:annotation>
			<xs:documentation>Orientation of the track's full data block relative to the track location at the track owner's display.</xs:documentation>
		</xs:annotation>
		<xs:restriction base="xs:string">
			<xs:enumeration value="E"/>
			<xs:enumeration value="N"/>
			<xs:enumeration value="NE"/>
			<xs:enumeration value="NW"/>
			<xs:enumeration value="S"/>
			<xs:enumeration value="SE"/>
			<xs:enumeration value="SW"/>
			<xs:enumeration value="UNDEFINED"/>
			<xs:enumeration value="W"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="StarsAircraftCategoryIndicatorType">
		<xs:annotation>
			<xs:documentation>Aircraft category/RNAV (when re-categorization is disabled) or Aircraft Wake Turbulence Category status (when Re-categorization is enabled) as displayed to the controller in the STARS data block.</xs:documentation>
		</xs:annotation>
		<xs:restriction base="fb:CharacterStringType">
			<xs:pattern value="[A-Z]"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="StarsFlightPlanDeletedIndicatorType">
		<xs:annotation>
			<xs:documentation>Indicates if a flight plan and associated data are deleted.</xs:documentation>
		</xs:annotation>
		<xs:restriction base="xs:string">
			<xs:enumeration value="DELETED">
				<xs:annotation>
					<xs:documentation>Deleted</xs:documentation>
				</xs:annotation>
			</xs:enumeration>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="StarsFlightPlanStatusType">
		<xs:annotation>
			<xs:documentation>Flight Plan Status: Pending, Active, Terminated, Passive.</xs:documentation>
		</xs:annotation>
		<xs:restriction base="xs:string">
			<xs:enumeration value="PENDING">
				<xs:annotation>
					<xs:documentation>Pending</xs:documentation>
				</xs:annotation>
			</xs:enumeration>
			<xs:enumeration value="ACTIVE">
				<xs:annotation>
					<xs:documentation>Active</xs:documentation>
				</xs:annotation>
			</xs:enumeration>
			<xs:enumeration value="TERMINATED">
				<xs:annotation>
					<xs:documentation>Terminated</xs:documentation>
				</xs:annotation>
			</xs:enumeration>
			<xs:enumeration value="PASSIVE">
				<xs:annotation>
					<xs:documentation>Passive</xs:documentation>
				</xs:annotation>
			</xs:enumeration>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="StarsFlightPlanSuspendedIndicatorType">
		<xs:annotation>
			<xs:documentation>Indicates if the Flight Plan is suspended.</xs:documentation>
		</xs:annotation>
		<xs:restriction base="xs:string">
			<xs:enumeration value="SUSPENDED">
				<xs:annotation>
					<xs:documentation>Suspended</xs:documentation>
				</xs:annotation>
			</xs:enumeration>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="TfmsUserCategoryType">
		<xs:annotation>
			<xs:documentation>Indicates the category of user operating the flight.</xs:documentation>
		</xs:annotation>
		<xs:restriction base="xs:string">
			<xs:enumeration value="AIR_TAXI">
				<xs:annotation>
					<xs:documentation>Air Taxi</xs:documentation>
				</xs:annotation>
			</xs:enumeration>
			<xs:enumeration value="CARGO">
				<xs:annotation>
					<xs:documentation>Cargo</xs:documentation>
				</xs:annotation>
			</xs:enumeration>
			<xs:enumeration value="COMMERCIAL">
				<xs:annotation>
					<xs:documentation>Commercial</xs:documentation>
				</xs:annotation>
			</xs:enumeration>
			<xs:enumeration value="GENERAL_AVIATION">
				<xs:annotation>
					<xs:documentation>General Aviation</xs:documentation>
				</xs:annotation>
			</xs:enumeration>
			<xs:enumeration value="MILITARY">
				<xs:annotation>
					<xs:documentation>Military</xs:documentation>
				</xs:annotation>
			</xs:enumeration>
			<xs:enumeration value="OTHER">
				<xs:annotation>
					<xs:documentation>Other</xs:documentation>
				</xs:annotation>
			</xs:enumeration>
			<xs:enumeration value="UNKNOWN">
				<xs:annotation>
					<xs:documentation>Unknown</xs:documentation>
				</xs:annotation>
			</xs:enumeration>
		</xs:restriction>
	</xs:simpleType>
	<xs:complexType name="EramAdaptedIcaoIndicatorType">
		<xs:annotation>
			<xs:documentation>Optionally adapted ICAO indicators that are transmitted when applicable.</xs:documentation>
		</xs:annotation>
		<xs:simpleContent>
			<xs:extension base="fb:CharacterStringType">
				<xs:attribute name="indicatorType" use="required" type="nas:AdaptedIndicatorTypeType">
					<xs:annotation>
						<xs:documentation>Specifies which ERAM adapted field (A-Y) the indicator comes from.</xs:documentation>
					</xs:annotation>
				</xs:attribute>
			</xs:extension>
		</xs:simpleContent>
	</xs:complexType>
	<xs:complexType name="FlightDelayType">
		<xs:annotation>
			<xs:documentation>Container that holds flight delay information</xs:documentation>
		</xs:annotation>
		<xs:sequence>
			<xs:element name="delayReason" type="nas:FlightDelayReasonListType" minOccurs="0" maxOccurs="1" nillable="true">
				<xs:annotation>
					<xs:documentation>For a delayed flight, it provides the reason(s) for the delay.</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="delayStatus" type="nas:FlightDelayStatusType" minOccurs="0" maxOccurs="1" nillable="true">
				<xs:annotation>
					<xs:documentation>Provides the delay status for a flight.</xs:documentation>
				</xs:annotation>
			</xs:element>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="NasCoordinationType">
		<xs:annotation>
			<xs:documentation>NAS extension to boundary crossing information: includes special handling for coordination time type.</xs:documentation>
		</xs:annotation>
		<xs:sequence>
			<xs:element name="coordinationFix" type="fb:SignificantPointChoiceType" minOccurs="0" maxOccurs="1" nillable="true">
				<xs:annotation>
					<xs:documentation>The fix to be used in conjunction with the Coordination Time so processing for this flight (and its trajectory) can be synchronized for the next sector/facility.  It coordinates the flight plan with the aircraft position.</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="coordinationTime" type="fb:DateTimeUtcType" minOccurs="0" maxOccurs="1" nillable="true">
				<xs:annotation>
					<xs:documentation>The time to be used in conjunction with the Coordination Fix so processing for this flight (and its trajectory) can be synchronized for the next sector/facility.  It   coordinates   the flight plan with the aircraft position.</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="coordinationTimeHandling" type="nas:CoordinationTimeTypeType" minOccurs="0" maxOccurs="1" nillable="true">
				<xs:annotation>
					<xs:documentation>The indicator for the type of Coordination Time.</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="delayTimeToAbsorb" type="fb:DurationType" minOccurs="0" maxOccurs="1" nillable="true">
				<xs:annotation>
					<xs:documentation>Indicates the amount of time that needs to be absorbed during the flight. It is corrective action for meeting the goal of Estimated Departure Clearance Time (EDCT), when flight is already active and needs to arrive at the destination later than originally planned.</xs:documentation>
				</xs:annotation>
			</xs:element>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="NasDiversionType">
		<xs:annotation>
			<xs:documentation>Diversion information for the flight.</xs:documentation>
		</xs:annotation>
		<xs:sequence>
			<xs:element name="cancellationLinkage" type="nas:NasDiversionCancellationLinkageType" minOccurs="0" maxOccurs="1" nillable="true">
				<xs:annotation>
					<xs:documentation>Contains information linking canceled flights to new flights.</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="diversionRecoveryIndicator" type="nas:DiversionRecoveryIndicatorType" minOccurs="0" maxOccurs="1" nillable="true">
				<xs:annotation>
					<xs:documentation>Indicates whether a flight is in diversion recovery.</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="state" type="nas:DiversionStateType" minOccurs="0" maxOccurs="1" nillable="true">
				<xs:annotation>
					<xs:documentation>Indicator used to define the diversion state of a flight.</xs:documentation>
				</xs:annotation>
			</xs:element>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="NasDiversionCancellationLinkageType">
		<xs:annotation>
			<xs:documentation>Contains information linking diversion flights to new flights.</xs:documentation>
		</xs:annotation>
		<xs:sequence>
			<xs:element name="cancelledTfmsFlightReference" type="fb:CountType" minOccurs="0" maxOccurs="1" nillable="true">
				<xs:annotation>
					<xs:documentation>The TFMS reference number of the canceled flight.</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="newTfmsFlightReference" type="fb:CountType" minOccurs="0" maxOccurs="1" nillable="true">
				<xs:annotation>
					<xs:documentation>The TFMS reference number of the new flight.</xs:documentation>
				</xs:annotation>
			</xs:element>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="NasFlightType">
		<xs:annotation>
			<xs:documentation>Extends core Flight object with NAS-specific information.</xs:documentation>
		</xs:annotation>
		<xs:complexContent>
			<xs:extension base="fb:FlightExtensionType">
				<xs:sequence>
					<xs:element name="additionalFlightInformation" type="nas:NameValueListType" minOccurs="0" maxOccurs="1" nillable="true">
						<xs:annotation>
							<xs:documentation>Additional information about a flight expressed in key-value pairs.
This element consists of an identification tag/indicator and the relevant value. This information is extra information about the flight that does not fall into some other predefined category.</xs:documentation>
						</xs:annotation>
					</xs:element>
					<xs:element name="asdexScratchpad1" type="fb:CharacterStringType" minOccurs="0" maxOccurs="1" nillable="true">
						<xs:annotation>
							<xs:documentation>First line of free form text obtained via manual tag.</xs:documentation>
						</xs:annotation>
					</xs:element>
					<xs:element name="asdexScratchpad2" type="fb:CharacterStringType" minOccurs="0" maxOccurs="1" nillable="true">
						<xs:annotation>
							<xs:documentation>Second line of free form text obtained via manual tag.</xs:documentation>
						</xs:annotation>
					</xs:element>
					<xs:element name="coordination" type="nas:NasCoordinationType" minOccurs="0" maxOccurs="1" nillable="true">
						<xs:annotation>
							<xs:documentation>NAS extension to boundary crossing information: includes special handling for coordination time type.     </xs:documentation>
						</xs:annotation>
					</xs:element>
					<xs:element name="diversion" type="nas:NasDiversionType" minOccurs="0" maxOccurs="1" nillable="true">
						<xs:annotation>
							<xs:documentation>Diversion information for the flight.</xs:documentation>
						</xs:annotation>
					</xs:element>
					<xs:element name="flightDelay" type="nas:FlightDelayType" minOccurs="0" maxOccurs="1" nillable="true">
						<xs:annotation>
							<xs:documentation>Contains information about flight delay and reason.</xs:documentation>
						</xs:annotation>
					</xs:element>
					<xs:element name="flightPlan" type="nas:NasFlightPlanType" minOccurs="0" maxOccurs="1" nillable="true">
						<xs:annotation>
							<xs:documentation>Contains information about the flight plan.</xs:documentation>
						</xs:annotation>
					</xs:element>
					<xs:element name="flightStatus" type="nas:NasFlightStatusType" minOccurs="0" maxOccurs="1" nillable="true">
						<xs:annotation>
							<xs:documentation>Identifies the aspect of the flight life cycle. </xs:documentation>
						</xs:annotation>
					</xs:element>
					<xs:element name="nasTmi" type="nas:NasTmiType" minOccurs="0" maxOccurs="1" nillable="true">
						<xs:annotation>
							<xs:documentation>NAS Traffic Management Initiative Information</xs:documentation>
						</xs:annotation>
					</xs:element>
					<xs:element name="starsDataBlock" type="nas:starsDataBlockType" minOccurs="0" maxOccurs="1" nillable="true">
						<xs:annotation>
							<xs:documentation>Container for STARS data block fields.</xs:documentation>
						</xs:annotation>
					</xs:element>
					<xs:element name="tfdmFlightCreationTime" type="fb:DateTimeUtcType" minOccurs="0" maxOccurs="1" nillable="true">
						<xs:annotation>
							<xs:documentation>The date and time at which a flight was originally created in the TFDM system.</xs:documentation>
						</xs:annotation>
					</xs:element>
					<xs:element name="tfmsFlightCreationTime" type="fb:DateTimeUtcType" minOccurs="0" maxOccurs="1" nillable="true">
						<xs:annotation>
							<xs:documentation> Indicates how long TFMS-Core has known of the flight.</xs:documentation>
						</xs:annotation>
					</xs:element>
					<xs:element name="userCategory" type="nas:TfmsUserCategoryType" minOccurs="0" maxOccurs="1" nillable="true">
						<xs:annotation>
							<xs:documentation>Indicates the category of user operating the flight.</xs:documentation>
						</xs:annotation>
					</xs:element>
				</xs:sequence>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
	<xs:complexType name="NasFlightCancellationLinkageType">
		<xs:annotation>
			<xs:documentation>Contains identification data linking a canceled flight to a new flight.</xs:documentation>
		</xs:annotation>
		<xs:sequence>
			<xs:element name="newAircraftIdentification" type="fb:AircraftIdentificationType" minOccurs="0" maxOccurs="1" nillable="true">
				<xs:annotation>
					<xs:documentation>Aircraft identification of the new flight.</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="newTfmsFlightReference" type="fb:CountType" minOccurs="0" maxOccurs="1" nillable="true">
				<xs:annotation>
					<xs:documentation>The TFMS reference number of the new flight.</xs:documentation>
				</xs:annotation>
			</xs:element>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="NasFlightIdentificationType">
		<xs:annotation>
			<xs:documentation>Extends flight identity to NAS specific identifiers.</xs:documentation>
		</xs:annotation>
		<xs:complexContent>
			<xs:extension base="fb:FlightIdentificationExtensionType">
				<xs:sequence>
					<xs:element name="adsbTargetId" type="nas:AdsbTargetIdentifierType" minOccurs="0" maxOccurs="1" nillable="true">
						<xs:annotation>
							<xs:documentation>ADS-B Flight ID is the Target Identification reported by the aircraft in FRN 12 of an ADS-B broadcast.</xs:documentation>
						</xs:annotation>
					</xs:element>
					<xs:element name="asdexManualAircraftIdentification" type="fb:AircraftIdentificationType" minOccurs="0" maxOccurs="1" nillable="true">
						<xs:annotation>
							<xs:documentation>Flight callsign, obtained via manual tag.</xs:documentation>
						</xs:annotation>
					</xs:element>
					<xs:element name="asdexTrackNumber" type="fb:CountType" minOccurs="0" maxOccurs="1" nillable="true">
						<xs:annotation>
							<xs:documentation>The track number assigned to the aircraft.</xs:documentation>
						</xs:annotation>
					</xs:element>
					<xs:element name="cancellationLinkage" type="nas:NasFlightCancellationLinkageType" minOccurs="0" maxOccurs="1" nillable="true">
						<xs:annotation>
							<xs:documentation>Contains information linking canceled flights to new flights.</xs:documentation>
						</xs:annotation>
					</xs:element>
					<xs:element name="computerId" type="nas:ComputerIdentificationType" minOccurs="0" maxOccurs="1" nillable="true">
						<xs:annotation>
							<xs:documentation>A unique identifier assigned by a particular system within a particular facility.  Typically ERAM within an ARTCC.</xs:documentation>
						</xs:annotation>
					</xs:element>
					<xs:element name="computerIdFacility" type="fb:AtcUnitReferenceType" minOccurs="0" maxOccurs="1" nillable="true">
						<xs:annotation>
							<xs:documentation>The facility that assigned the computer identifier.</xs:documentation>
						</xs:annotation>
					</xs:element>
					<xs:element name="computerIdPrevious" type="nas:ComputerIdentificationType" minOccurs="0" maxOccurs="1" nillable="true">
						<xs:annotation>
							<xs:documentation>Specifies the previous computer identification value when a change is made.</xs:documentation>
						</xs:annotation>
					</xs:element>
					<xs:element name="computerIdSystem" type="nas:ComputerIdSystemType" minOccurs="0" maxOccurs="1" nillable="true">
						<xs:annotation>
							<xs:documentation>The system that assigned the computer identifier.</xs:documentation>
						</xs:annotation>
					</xs:element>
					<xs:element name="eramId" type="fb:CharacterStringType" minOccurs="0" maxOccurs="1" nillable="true">
						<xs:annotation>
							<xs:documentation>ERAM Unique Flight Plan Identifier.</xs:documentation>
						</xs:annotation>
					</xs:element>
					<xs:element name="sfdpsId" type="fb:CharacterStringType" minOccurs="0" maxOccurs="1" nillable="true">
						<xs:annotation>
							<xs:documentation>SFDPS Unique Identifier.</xs:documentation>
						</xs:annotation>
					</xs:element>
					<xs:element name="siteSpecificPlanId" type="fb:CountType" minOccurs="0" maxOccurs="1" nillable="true">
						<xs:annotation>
							<xs:documentation>Site Specific Plan Identifier is a unique ID for each system plan in each ERAM facility.</xs:documentation>
						</xs:annotation>
					</xs:element>
					<xs:element name="siteSpecificPlanIdPrevious" type="fb:CountType" minOccurs="0" maxOccurs="1" nillable="true">
						<xs:annotation>
							<xs:documentation>Specifies the previous site specific plan identifier value when a change is made.</xs:documentation>
						</xs:annotation>
					</xs:element>
					<xs:element name="stddsSurfaceTrackIdentifier" type="fb:CountType" minOccurs="0" maxOccurs="1" nillable="true">
						<xs:annotation>
							<xs:documentation>Unique identifier assigned by SWIM Terminal Data Distribution System (STDDS).</xs:documentation>
						</xs:annotation>
					</xs:element>
					<xs:element name="tfdmId" type="fb:UniversallyUniqueIdentifierType" minOccurs="0" maxOccurs="1" nillable="true">
						<xs:annotation>
							<xs:documentation>TFDM Unique Identifier with the format 8-4-4-4-12 hex digits generated in accordance with RFC 4122.</xs:documentation>
						</xs:annotation>
					</xs:element>
					<xs:element name="tfdmIdCreatorAirport" type="fb:LocationIndicatorType" minOccurs="0" maxOccurs="1" nillable="true">
						<xs:annotation>
							<xs:documentation>TFDM Id Creator Airport with an ICAO Aerodrome format.</xs:documentation>
						</xs:annotation>
					</xs:element>
					<xs:element name="tfmsDatabaseKey" type="fb:CharacterStringType" minOccurs="0" maxOccurs="1" nillable="true">
						<xs:annotation>
							<xs:documentation>Oracle key of the flight in TFMS database.  </xs:documentation>
						</xs:annotation>
					</xs:element>
					<xs:element name="tfmsFlightReference" type="fb:CountType" minOccurs="0" maxOccurs="1" nillable="true">
						<xs:annotation>
							<xs:documentation>TFMS Unique Identifier.</xs:documentation>
						</xs:annotation>
					</xs:element>
					<xs:element name="tfmsFlightReferencePrevious" type="fb:CountType" minOccurs="0" maxOccurs="1" nillable="true">
						<xs:annotation>
							<xs:documentation>Specifies the previous TFMS Unique Identifier value when a change is made.</xs:documentation>
						</xs:annotation>
					</xs:element>
				</xs:sequence>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
	<xs:complexType name="NasFlightPlanType">
		<xs:annotation>
			<xs:documentation>Container for flight plan information.</xs:documentation>
		</xs:annotation>
		<xs:sequence>
			<xs:element name="eramAdaptedIcaoIndicator" type="nas:EramAdaptedIcaoIndicatorType" minOccurs="0" maxOccurs="25" nillable="true">
				<xs:annotation>
					<xs:documentation>Optionally adapted ICAO indicators that are transmitted when applicable.</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="flightPlanRemarks" type="fb:CharacterStringType" minOccurs="0" maxOccurs="1" nillable="true">
				<xs:annotation>
					<xs:documentation> NAS Flight Plan Field 11 remarks processed by the Traffic Flow Management System (TFMS) and used for TFM purposes. </xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="flightPlanRevisionNumber" type="nas:FlightPlanRevisionNumberType" minOccurs="0" maxOccurs="1" nillable="true">
				<xs:annotation>
					<xs:documentation>ERAM assigned flight plan revision number.</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="sfdpsFlightPlanSequenceNumber" type="fb:CountType" minOccurs="0" maxOccurs="1" nillable="true">
				<xs:annotation>
					<xs:documentation>Contains the sequence number for the flight plan as assigned by SFDPS. This number should increment every time a flight plan is modified.</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="starsFlightPlanDeletedIndicator" type="nas:StarsFlightPlanDeletedIndicatorType" minOccurs="0" maxOccurs="1" nillable="true">
				<xs:annotation>
					<xs:documentation>Indicates if a flight plan and associated data are deleted.</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="starsFlightPlanIndex" type="fb:CountType" minOccurs="0" maxOccurs="1" nillable="true">
				<xs:annotation>
					<xs:documentation>STARS system flight plan index.</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="starsFlightPlanStatus" type="nas:StarsFlightPlanStatusType" minOccurs="0" maxOccurs="1" nillable="true">
				<xs:annotation>
					<xs:documentation>Flight Plan Status: Pending, Active, Terminated, Passive.</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="starsFlightPlanSuspendedIndicator" type="nas:StarsFlightPlanSuspendedIndicatorType" minOccurs="0" maxOccurs="1" nillable="true">
				<xs:annotation>
					<xs:documentation>Flight plan suspended.</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="tfdmIdOfFlightPlanUsedForSurfaceManagement" type="fb:UniversallyUniqueIdentifierType" minOccurs="0" maxOccurs="1" nillable="true">
				<xs:annotation>
					<xs:documentation>Presence of this element indicates that TFDM Surface Management does not consider this flight plan as the primary plan for the flight.  TFDM Surface Management considers this flight plan to be a duplicate of another flight plan, where the other flight plan is considered the primary plan for the flight.  This field provides the tfdmId of the flight plan that is primary.</xs:documentation>
				</xs:annotation>
			</xs:element>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="starsDataBlockType">
		<xs:annotation>
			<xs:documentation>Container for STARS data block fields.</xs:documentation>
		</xs:annotation>
		<xs:sequence>
			<xs:element name="aircraftCategory" type="nas:StarsAircraftCategoryIndicatorType" minOccurs="0" maxOccurs="1" nillable="true">
				<xs:annotation>
					<xs:documentation>Aircraft category/RNAV (when re-categorization is disabled) or Aircraft Wake Turbulence Category status (when Re-categorization is enabled) as displayed to the controller in the STARS data block.</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="indicator" type="nas:DataBlockIndicatorListType" minOccurs="0" maxOccurs="1" nillable="true">
				<xs:annotation>
					<xs:documentation>Provides a list of currently active indicators in the track's data block.</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="leaderLineDirection" type="nas:LeaderLineDirectionType" minOccurs="0" maxOccurs="1" nillable="true">
				<xs:annotation>
					<xs:documentation>Orientation of the track's full data block relative to the track location at the track owner's display.</xs:documentation>
				</xs:annotation>
			</xs:element>
		</xs:sequence>
	</xs:complexType>
</xs:schema>